#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login

#config/routes.yml
gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh